name: Run Notebook

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notebook:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert matplotlib seaborn scikit-learn
        pip install -r requirements.txt
        
    - name: Execute notebook
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        jupyter nbconvert --to notebook --execute TrashNetClassification.ipynb --output executed_notebook.ipynb
        
    - name: Upload executed notebook
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebook
        path: executed_notebook.ipynb
        
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: best_model.pth